#  les ressources de type asws:Roi 

PREFIX asws: <http://www.asws.com/rois#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


# Q2
SELECT ?nom
WHERE {
  ?roi a asws:Roi ;
	   asws:nom ?nom .
	   OPTIONAL {?roi asws:datenaiss ?date . }
}